 services:
  server:
    build: ./server
    restart: always
    command: sh -c "/server/wait-for-db.sh && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/server
    ports:
      - "8000:8000"