FROM python:3.10
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /server
RUN apt update
RUN apt -y install netcat
RUN pip install --upgrade pip
RUN pip install psycopg2 Django
COPY . /server/